language: ruby
cache: bundler
sudo: false
rvm: 
  - 2.2
before_install:
  - gem update --system
  - gem install bundler
before_script:
  - cp 'config/mongoid_sample.yml' 'config/mongoid.yml'
  - sleep 10
  - mongo testing
services:
  - mongodb

